services:
  accounts:
    image: "rakeshrout/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - gutsbank
  loans:
    image: "rakeshrout/loans:v1"
    container_name: laons-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - gutsbank
  cards:
    image: "rakeshrout/cards:v1"
    container_name: cards-ms
    ports:
      - 8082:8082
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - gutsbank
networks:
  gutsbank:
    driver: "bridge"