build:
  version: "1.0"

cards:
  message: "Welcome to Guts Bank Cards related Local APIs"
  email_name:
    name: "Guts - Developer"
    email: "gutsblackswordsman96@gmail.com"
  mobile_number:
    - (999)345-1244
    - (999)321-8764