build:
  version: "3.0"

loans:
  message: "Welcome to Guts bank Loans QA APIs"
  email_name:
    name: "John - QA Lead"
    email: "John@doe.com"
  mobile_number:
    - (222)543-5644
    - (222)345-6752